- name: deploy the docker container
  hosts: 172.31.57.154
  tasks:
  - name: stop old container
    command: docker stop tomcat-test
    ignore_errors: yes
  - name: delete old container
    command: docker rm  tomcat-test
    ignore_errors: yes
  - name: delete old image 
    command: docker rmi 137265817571.dkr.ecr.us-east-1.amazonaws.com/test-tomcat
    ignore_errors: yes

  - name: create container
    command: docker run -p 8080:8080 --name tomcat-test 137265817571.dkr.ecr.us-east-1.amazonaws.com/test-tomcat
    
